language: go

env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=amd64

install:
    - export GOPATH=`pwd`
    - mkdir -p bin

script:
    - go build -o bin/coscale-cli-{$GIMME_OS} coscale
