language: go
go:
- 1.7
env:
- MY_GOOS=linux MY_GOARCH=amd64 EXTENSION=
- MY_GOOS=windows MY_GOARCH=amd64 EXTENSION=.exe
- MY_GOOS=darwin MY_GOARCH=amd64 EXTENSION=-osx
before_install:
- export GOOS="${MY_GOOS}"
- export GOARCH="${MY_GOARCH}"
install:
- export GOPATH=`pwd`
- export CGO_ENABLED=0
- mkdir -p bin
script:
- if [ "$GOOS" == "linux" ]; then
    go test -timeout 20m -a -v coscale/... || travis_terminate 1;
  fi
- go build -a -tags netgo -ldflags '-w' -o bin/coscale-cli$EXTENSION coscale
deploy:
  provider: releases
  api_key:
    secure: YePODQlTlJO5VZnhJzA5+1eEK6D6s3dJXVrKDU30/8qPVIleS6M4YoS7o7/9LkvDOc7KLYCgYbEqWmAnL1eyCyRGHrfhLhs9yoPEcRe6P4NxwMyUmPtpqRbXcaRNJm/NwaLNX9QK21VW0kdmEjfmnyGSaO7WZRyP5xF+Mss2NaQinZySG0tSzc/HiHVB1fA22/WcQb0/G2Un59sA94Jy8Sd0tmz0VfYNiagMsrKRW+cNHUbx96wV2nCetbtRfmjYIn4D1SV9sS5N7X4q8dcxXhXzRebPkPiYyOx9fYaco6uD+GkOHMoAjUNKUKGyiR+FBDkWFVPRF47F4rLNtxc2EKlFfjZaThQCSAARh6vIku5X0vF164Lowc3ihb0t51sZALcZ6MfoEKa9LcZtk0JnrLRQj9FrsowajSZ4WsmmwrJrm1LlyDanUJxTRwIx7NkX2bm0bwJO7t4c01xPqHmjEnR9KY6vn1gCC2Jg3kQ4preNfYbYjB3mGeuzoK3MmfaVDMPDyTVkQRpyt+zuq1vkMvR6JCoG/j3fSJLvpmqqw2YWSAmLNk4pP3A511LH/Xz1m64rME7d5upZ5hqWAyE7l4oslvLHwJysrKK6qsIcURAbwgsDFRBY0YAPGOLri8aBTH+daTU+ydzyMOX2ek+oulifHnjsQLxYE6JdWoswIvA=
  file: bin/coscale-cli$EXTENSION
  skip_cleanup: true
  on:
    tags: true
